In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, Flatten
import pydot

In [7]:
#Importing the Data
digit_data = pd.read_csv('train.csv')
X_test = pd.read_csv('test.csv')

In [74]:
digit_data.values

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [7, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [75]:
X_train = digit_data.drop('label', axis=1) /255.0
y_train = digit_data['label']

In [76]:
X_train.shape

(42000, 784)

In [77]:
class_names = [0,1,2,3,4,5,6,7,8,9]

In [78]:
class_names[y_train[10]]

8

In [79]:
model = keras.models.Sequential([
    Flatten(input_shape=[784]),
    Dense(300,activation='relu'),
    Dense(100,activation='relu'),
    Dense(10,activation='softmax')
])

In [80]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_7 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_21 (Dense)             (None, 300)               235500    
_________________________________________________________________
dense_22 (Dense)             (None, 100)               30100     
_________________________________________________________________
dense_23 (Dense)             (None, 10)                1010      
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


In [81]:
model.layers

In [82]:
model.layers[1].name

'dense_21'

In [83]:
weights, biases = model.layers[1].get_weights()

In [84]:
weights

array([[-0.01323024,  0.0297045 , -0.06149854, ..., -0.05665134,
         0.06567675,  0.02564642],
       [ 0.05571403, -0.0397069 , -0.05531481, ..., -0.03190142,
        -0.05579529,  0.00511274],
       [ 0.0677316 ,  0.01424887, -0.00752091, ...,  0.03243157,
         0.02167271,  0.0114958 ],
       ...,
       [ 0.01233703, -0.07384609,  0.04177248, ...,  0.035254  ,
        -0.03679354,  0.01246992],
       [ 0.01556972,  0.0107758 , -0.00896987, ...,  0.07035199,
        -0.0544989 , -0.01918253],
       [-0.07002307, -0.02340953, -0.03568223, ..., -0.04516084,
         0.04210074, -0.00062413]], dtype=float32)

In [85]:
biases

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [86]:
weights.shape

(784, 300)

In [87]:
biases.shape

(300,)

In [88]:
model.compile(loss='sparse_categorical_crossentropy',
    optimizer='sgd',
    metrics=['accuracy'])

In [90]:
digits = model.fit(X_train, y_train,
    epochs=40,
    validation_split=0.2)

Epoch 1/40
1050/1050 [==============================] - 1s 1ms/step - loss: 0.0395 - accuracy: 0.9913 - val_loss: 0.0960 - val_accuracy: 0.9705
Epoch 2/40
1050/1050 [==============================] - 1s 1ms/step - loss: 0.0376 - accuracy: 0.9919 - val_loss: 0.0922 - val_accuracy: 0.9719
Epoch 3/40
1050/1050 [==============================] - 1s 1ms/step - loss: 0.0356 - accuracy: 0.9920 - val_loss: 0.0926 - val_accuracy: 0.9719
Epoch 4/40
1050/1050 [==============================] - 1s 1ms/step - loss: 0.0337 - accuracy: 0.9929 - val_loss: 0.0930 - val_accuracy: 0.9719
Epoch 5/40
1050/1050 [==============================] - 1s 1ms/step - loss: 0.0319 - accuracy: 0.9934 - val_loss: 0.0906 - val_accuracy: 0.9731
Epoch 6/40
1050/1050 [==============================] - 1s 1ms/step - loss: 0.0305 - accuracy: 0.9936 - val_loss: 0.0916 - val_accuracy: 0.9723
Epoch 7/40
1050/1050 [==============================] - 1s 1ms/step - loss: 0.0291 - accuracy: 0.9940 - val_loss: 0.0897 - val_accuracy: