In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.image as mpimg
from datetime import datetime

### Let's start by processing the colored cats & dog data 

In [2]:
cats_3 = np.load('cats_1000_128_128_3.npy')

In [3]:
dogs_3 = np.load('dogs_1000_128_128_3.npy')

In [4]:
cats_3.shape # investigate the shape

(1000, 128, 128, 3)

In [5]:
dogs_3.shape # investigate the shape

(1000, 128, 128, 3)

In [6]:
cats_3.dtype, dogs_3.dtype # look at dtype

(dtype('float64'), dtype('float64'))

In [7]:
dogs_3_y= np.repeat(1,1000) # Let's create training labels for dogs 

In [8]:
cats_3_y = np.repeat(0,1000) # Let's create training labels for cats

In [9]:
# create labels 1=dog, 0=cat
# combine into one array for training labels
y_train_3 = np.concatenate((dogs_3_y, cats_3_y),axis=0)
y_train_3

array([1, 1, 1, ..., 0, 0, 0])

In [10]:
# combine dogs & cats for training 
x_train_3 = np.concatenate((dogs_3,cats_3),axis=0)
x_train_3

array([[[[118., 116., 128.],
         [106., 104., 119.],
         [120., 118., 131.],
         ...,
         [139., 141., 153.],
         [133., 135., 147.],
         [133., 133., 142.]],

        [[122., 120., 132.],
         [109., 107., 122.],
         [122., 120., 133.],
         ...,
         [141., 143., 155.],
         [137., 138., 151.],
         [136., 136., 145.]],

        [[125., 123., 135.],
         [112., 110., 125.],
         [123., 121., 134.],
         ...,
         [142., 144., 156.],
         [139., 141., 153.],
         [139., 142., 149.]],

        ...,

        [[ 70.,  84.,  87.],
         [ 87.,  90.,  96.],
         [ 73.,  78.,  82.],
         ...,
         [ 67.,  77.,  79.],
         [ 60.,  69.,  72.],
         [ 63.,  73.,  75.]],

        [[ 73.,  78.,  82.],
         [ 69.,  77.,  80.],
         [ 72.,  82.,  84.],
         ...,
         [ 63.,  72.,  77.],
         [ 60.,  69.,  74.],
         [ 75.,  85.,  87.]],

        [[ 68.,  73.,  77.],
       

In [11]:
# create class names
class_names= ['cats','dogs']

### create train, validate & test set

In [12]:
# create train, validate & test set
from sklearn.model_selection import train_test_split

In [13]:
# initial test train split for 3 colors
x_train_3, x_test_3, y_train_3, y_test_3 = train_test_split(x_train_3, y_train_3, test_size=.30, random_state=55)

In [14]:
# train vs validation set
X_train_3, x_valid_3, y_train_3, y_valid_3 = train_test_split(x_train_3,y_train_3, test_size=.20, random_state=55)

In [15]:
X_train_3.shape

(1120, 128, 128, 3)

#### 1st Model

In [16]:
#clear keras session
tf.keras.backend.clear_session()

In [17]:
model1 = keras.models.Sequential([
    keras.layers.Conv2D(filters= 64, kernel_size=(3,3),strides=1, activation='relu', padding='same',
                       input_shape=[128,128,3]),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(pool_size=2, strides=2),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2, strides=2),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2, strides=2),
    keras.layers.Flatten(),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(1000, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(1, activation='sigmoid')
])

In [18]:
model1.compile(loss="binary_crossentropy", optimizer="nadam", metrics=["accuracy"])

# fit model
time_start = datetime.now()
history1 = model1.fit(X_train_3, y_train_3, epochs=5, validation_data=(x_valid_3, y_valid_3))
time_end = datetime.now()
time_elapsed = time_end - time_start

print('Time elapsed')
print(time_elapsed)
print("Fit model on training data")
history1.history

Epoch 1/5
35/35 [==============================] - 172s 5s/step - loss: 0.8502 - accuracy: 0.5625 - val_loss: 17.6841 - val_accuracy: 0.4464
Epoch 2/5
35/35 [==============================] - 173s 5s/step - loss: 0.7308 - accuracy: 0.6268 - val_loss: 4.8494 - val_accuracy: 0.5036
Epoch 3/5
35/35 [==============================] - 173s 5s/step - loss: 0.6902 - accuracy: 0.6277 - val_loss: 0.9702 - val_accuracy: 0.5893
Epoch 4/5
35/35 [==============================] - 174s 5s/step - loss: 0.6238 - accuracy: 0.6857 - val_loss: 0.7659 - val_accuracy: 0.6143
Epoch 5/5
35/35 [==============================] - 173s 5s/step - loss: 0.5363 - accuracy: 0.7393 - val_loss: 0.7324 - val_accuracy: 0.6179
Time elapsed
0:14:54.830526
Fit model on training data


{'loss': [0.8502169847488403,
  0.7308361530303955,
  0.6902106404304504,
  0.6237974166870117,
  0.5363139510154724],
 'accuracy': [0.5625,
  0.6267856955528259,
  0.6276785731315613,
  0.6857143044471741,
  0.7392857074737549],
 'val_loss': [17.68406105041504,
  4.849357604980469,
  0.9702354669570923,
  0.765922486782074,
  0.7324285507202148],
 'val_accuracy': [0.4464285671710968,
  0.5035714507102966,
  0.5892857313156128,
  0.6142857074737549,
  0.6178571581840515]}

In [19]:
print("Evaluate on test data")
score = model1.evaluate(x_test_3, y_test_3)
predictions = model1.predict(x_test_3)
predictions

Evaluate on test data
19/19 [==============================] - 19s 995ms/step - loss: 0.6649 - accuracy: 0.6567


array([[9.13617790e-01],
       [7.91907549e-01],
       [9.02791798e-01],
       [1.92951441e-01],
       [7.36265957e-01],
       [8.15220594e-01],
       [5.89085281e-01],
       [5.02529442e-02],
       [4.67624545e-01],
       [8.21565509e-01],
       [9.93378818e-01],
       [9.77468312e-01],
       [2.66157895e-01],
       [9.08523679e-01],
       [2.20675051e-01],
       [6.72152162e-01],
       [8.87636662e-01],
       [5.51730573e-01],
       [2.25377381e-01],
       [3.75881314e-01],
       [4.97575462e-01],
       [1.26660943e-01],
       [1.13770306e-01],
       [1.96513623e-01],
       [6.05705082e-01],
       [6.28522396e-01],
       [1.02216125e-01],
       [4.31057334e-01],
       [2.65966833e-01],
       [5.70265472e-01],
       [7.92578220e-01],
       [7.71405816e-01],
       [1.86598718e-01],
       [3.45297754e-01],
       [7.44694948e-01],
       [7.48724103e-01],
       [4.99024242e-01],
       [4.46655631e-01],
       [7.31705070e-01],
       [8.63397837e-01],


#### 2nd Model

In [20]:
#clear keras session
tf.keras.backend.clear_session()

In [21]:
model2 = keras.models.Sequential([
    keras.layers.Conv2D(filters= 64, kernel_size=3,strides=1, activation='relu', padding='same',
                       input_shape=[128,128,3]),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Flatten(),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(1000, activation='relu'),
    keras.layers.Dropout(0.25),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dropout(0.25),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(1, activation='sigmoid')
])

In [22]:
optimizer = keras.optimizers.SGD(lr=.02, momentum=0.9, decay=0.01)
model2.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

In [23]:
# fit model
time_start = datetime.now()
history2 = model2.fit(X_train_3, y_train_3, epochs=5, validation_data=(x_valid_3, y_valid_3))
time_end = datetime.now()
time_elapsed = time_end - time_start

print('Time elapsed')
print(time_elapsed)
print("Fit model on training data")
history2.history

Epoch 1/5
35/35 [==============================] - 158s 5s/step - loss: 0.8018 - accuracy: 0.5420 - val_loss: 39.4376 - val_accuracy: 0.4500
Epoch 2/5
35/35 [==============================] - 202s 6s/step - loss: 0.6893 - accuracy: 0.5911 - val_loss: 2.1800 - val_accuracy: 0.4679
Epoch 3/5
35/35 [==============================] - 182s 5s/step - loss: 0.6778 - accuracy: 0.6080 - val_loss: 2.4579 - val_accuracy: 0.4536
Epoch 4/5
35/35 [==============================] - 160s 5s/step - loss: 0.6441 - accuracy: 0.6411 - val_loss: 1.2329 - val_accuracy: 0.4857
Epoch 5/5
35/35 [==============================] - 155s 4s/step - loss: 0.6087 - accuracy: 0.6714 - val_loss: 1.0023 - val_accuracy: 0.5643
Time elapsed
0:14:44.371246
Fit model on training data


{'loss': [0.8018324971199036,
  0.6893308162689209,
  0.6778269410133362,
  0.6440851092338562,
  0.608709990978241],
 'accuracy': [0.5419642925262451,
  0.5910714268684387,
  0.6080357432365417,
  0.6410714387893677,
  0.6714285612106323],
 'val_loss': [39.43761444091797,
  2.1800031661987305,
  2.457854747772217,
  1.2328927516937256,
  1.0023380517959595],
 'val_accuracy': [0.44999998807907104,
  0.46785715222358704,
  0.4535714387893677,
  0.48571428656578064,
  0.5642856955528259]}

In [24]:
print("Evaluate on test data")
score = model2.evaluate(x_test_3, y_test_3)
predictions = model2.predict(x_test_3)
predictions

Evaluate on test data
19/19 [==============================] - 20s 1s/step - loss: 0.9357 - accuracy: 0.5533


array([[0.6560199 ],
       [0.14111128],
       [0.87196076],
       [0.65350294],
       [0.86115384],
       [0.14601701],
       [0.5800932 ],
       [0.995579  ],
       [0.9943064 ],
       [0.67769957],
       [0.97294164],
       [0.9795412 ],
       [0.3620175 ],
       [0.99598306],
       [0.20431256],
       [0.6910225 ],
       [0.98446006],
       [0.7378739 ],
       [0.6006617 ],
       [0.99544483],
       [0.39914304],
       [0.9948431 ],
       [0.7840255 ],
       [0.96090794],
       [0.641858  ],
       [0.7074018 ],
       [0.98324287],
       [0.34764624],
       [0.8697827 ],
       [0.9897436 ],
       [0.8481445 ],
       [0.8974323 ],
       [0.7335695 ],
       [0.8290092 ],
       [0.8937237 ],
       [0.99495405],
       [0.93880147],
       [0.48411888],
       [0.83951485],
       [0.6566617 ],
       [0.5496788 ],
       [0.5550746 ],
       [0.94756067],
       [0.9478549 ],
       [0.27313763],
       [0.6851419 ],
       [0.999775  ],
       [0.985

#### 3rd Model

In [25]:
#clear keras session
tf.keras.backend.clear_session()

In [26]:
model3 = keras.models.Sequential([
    keras.layers.Conv2D(filters= 64, kernel_size=3,strides=1, activation='relu', padding='same',
                       input_shape=[128,128,3]),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Flatten(),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(1000, activation='relu'),
    keras.layers.Dropout(0.25),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dropout(0.25),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(1, activation='sigmoid')
])

In [27]:
optimizer=tf.keras.optimizers.Adam(learning_rate=0.001,
                                                 beta_1=0.9,
                                                 beta_2=0.999)
model3.compile(loss=tf.keras.losses.binary_crossentropy,
              optimizer=optimizer,
              metrics=['accuracy'])

In [28]:
# fit model
time_start = datetime.now()
history3 = model3.fit(X_train_3, y_train_3, epochs=5, validation_data=(x_valid_3, y_valid_3))
time_end = datetime.now()
time_elapsed = time_end - time_start

print('Time elapsed')
print(time_elapsed)
print("Fit model on training data")
history3.history

Epoch 1/5
35/35 [==============================] - 175s 5s/step - loss: 0.8028 - accuracy: 0.5536 - val_loss: 14.3262 - val_accuracy: 0.4464
Epoch 2/5
35/35 [==============================] - 184s 5s/step - loss: 0.6629 - accuracy: 0.6286 - val_loss: 8.4111 - val_accuracy: 0.4464
Epoch 3/5
35/35 [==============================] - 181s 5s/step - loss: 0.5889 - accuracy: 0.6946 - val_loss: 1.0269 - val_accuracy: 0.5964
Epoch 4/5
35/35 [==============================] - 169s 5s/step - loss: 0.4916 - accuracy: 0.7634 - val_loss: 0.6641 - val_accuracy: 0.6643
Epoch 5/5
35/35 [==============================] - 169s 5s/step - loss: 0.4253 - accuracy: 0.8054 - val_loss: 0.7821 - val_accuracy: 0.5786
Time elapsed
0:15:05.519694
Fit model on training data


{'loss': [0.8027859330177307,
  0.6628555655479431,
  0.5889459848403931,
  0.49156373739242554,
  0.42526164650917053],
 'accuracy': [0.5535714030265808,
  0.6285714507102966,
  0.6946428418159485,
  0.7633928656578064,
  0.8053571581840515],
 'val_loss': [14.326237678527832,
  8.411081314086914,
  1.026942491531372,
  0.6640943884849548,
  0.7821476459503174],
 'val_accuracy': [0.4464285671710968,
  0.4464285671710968,
  0.5964285731315613,
  0.6642857193946838,
  0.5785714387893677]}

In [29]:
print("Evaluate on test data")
score = model3.evaluate(x_test_3, y_test_3)
predictions = model3.predict(x_test_3)
predictions

Evaluate on test data
19/19 [==============================] - 21s 1s/step - loss: 0.7477 - accuracy: 0.6350


array([[8.02692652e-01],
       [2.46953219e-01],
       [7.56223440e-01],
       [1.00886464e-01],
       [7.47440100e-01],
       [8.82776678e-01],
       [4.01052356e-01],
       [1.83052123e-02],
       [2.03719497e-01],
       [5.55154085e-02],
       [9.57697093e-01],
       [9.93121028e-01],
       [8.70021880e-02],
       [3.73911947e-01],
       [5.03649771e-01],
       [5.57969630e-01],
       [6.64475858e-01],
       [2.48622000e-01],
       [7.19326437e-01],
       [1.28753603e-01],
       [6.90443695e-01],
       [6.92101419e-02],
       [4.07087326e-01],
       [9.69948769e-02],
       [2.25526094e-01],
       [4.87177372e-01],
       [7.14835525e-02],
       [9.17809248e-01],
       [3.96629870e-02],
       [3.70361507e-01],
       [2.57592380e-01],
       [5.63226819e-01],
       [5.86489081e-01],
       [2.47468501e-01],
       [7.71460176e-01],
       [9.74035978e-01],
       [4.51720566e-01],
       [2.49079108e-01],
       [3.91290724e-01],
       [5.95545650e-01],


#### 4th Model

In [30]:
#clear keras session
tf.keras.backend.clear_session()

In [31]:
model4 = keras.models.Sequential([
    keras.layers.Conv2D(filters= 64, kernel_size=(3,3),strides=1, activation='relu', padding='same',
                       input_shape=[128,128,3]),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Flatten(),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(1000, activation='relu'),
    keras.layers.Dropout(0.25),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dropout(0.25),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(1, activation='sigmoid')
])

In [32]:
optimizer=tf.keras.optimizers.Adam(learning_rate=0.001,
                                                 beta_1=0.9,
                                                 beta_2=0.999)
model4.compile(loss=tf.keras.losses.binary_crossentropy,
              optimizer=optimizer,
              metrics=['accuracy'])

In [33]:
# fit model
time_start = datetime.now()
history4 = model4.fit(X_train_3, y_train_3, epochs=30, validation_data=(x_valid_3, y_valid_3))
time_end = datetime.now()
time_elapsed = time_end - time_start

print('Time elapsed')
print(time_elapsed)
print("Fit model on training data")
history4.history

Epoch 1/30
35/35 [==============================] - 144s 4s/step - loss: 0.8565 - accuracy: 0.5384 - val_loss: 18.0328 - val_accuracy: 0.5536
Epoch 2/30
35/35 [==============================] - 129s 4s/step - loss: 0.7203 - accuracy: 0.5866 - val_loss: 1.7445 - val_accuracy: 0.5571
Epoch 3/30
35/35 [==============================] - 124s 4s/step - loss: 0.6604 - accuracy: 0.6330 - val_loss: 1.1089 - val_accuracy: 0.5786
Epoch 4/30
35/35 [==============================] - 708s 20s/step - loss: 0.6846 - accuracy: 0.6277 - val_loss: 0.8587 - val_accuracy: 0.5214
Epoch 5/30
35/35 [==============================] - 101s 3s/step - loss: 0.6406 - accuracy: 0.6598 - val_loss: 0.8763 - val_accuracy: 0.4464
Epoch 6/30
35/35 [==============================] - 127s 4s/step - loss: 0.5876 - accuracy: 0.6938 - val_loss: 0.7558 - val_accuracy: 0.5464
Epoch 7/30
35/35 [==============================] - 127s 4s/step - loss: 0.5653 - accuracy: 0.6938 - val_loss: 0.9069 - val_accuracy: 0.4964
Epoch 8/30


{'loss': [0.8564894795417786,
  0.7203150987625122,
  0.6604405045509338,
  0.6845935583114624,
  0.6405786275863647,
  0.5875927805900574,
  0.5652638077735901,
  0.535964846611023,
  0.5395981073379517,
  0.4968244731426239,
  0.5158067941665649,
  0.45258888602256775,
  0.400858610868454,
  0.30670905113220215,
  0.26361045241355896,
  0.24466781318187714,
  0.21293088793754578,
  0.2971595227718353,
  0.2858641445636749,
  0.20415300130844116,
  0.18281157314777374,
  0.13374827802181244,
  0.13721121847629547,
  0.13007457554340363,
  0.1451040506362915,
  0.1320284605026245,
  0.13919778168201447,
  0.09111028909683228,
  0.09898245334625244,
  0.06765560060739517],
 'accuracy': [0.5383928418159485,
  0.5866071581840515,
  0.6330357193946838,
  0.6276785731315613,
  0.6598214507102966,
  0.6937500238418579,
  0.6937500238418579,
  0.71875,
  0.7303571701049805,
  0.7562500238418579,
  0.7428571581840515,
  0.7821428775787354,
  0.8169642686843872,
  0.8687499761581421,
  0.904464

In [34]:
print("Evaluate on test data")
score = model4.evaluate(x_test_3, y_test_3)
predictions = model4.predict(x_test_3)
predictions

Evaluate on test data
19/19 [==============================] - 18s 932ms/step - loss: 1.3748 - accuracy: 0.5733


array([[9.8527610e-01],
       [4.7247368e-01],
       [9.7477394e-01],
       [4.3824822e-02],
       [9.9804759e-01],
       [9.3688351e-01],
       [8.9994752e-01],
       [4.3219739e-01],
       [9.9950165e-01],
       [9.9980265e-01],
       [9.9996847e-01],
       [9.9107862e-01],
       [1.2566411e-01],
       [9.9878013e-01],
       [6.5630627e-01],
       [8.4125024e-01],
       [9.6222806e-01],
       [6.2735623e-01],
       [8.6651689e-01],
       [9.5977807e-01],
       [4.8844996e-01],
       [9.9153316e-01],
       [4.7929168e-02],
       [9.8499930e-01],
       [4.5735171e-01],
       [9.3870026e-01],
       [6.8305349e-01],
       [1.4117077e-01],
       [9.8209226e-01],
       [8.2709706e-01],
       [3.7460819e-01],
       [9.9992979e-01],
       [7.5503731e-01],
       [9.9914044e-01],
       [9.9472332e-01],
       [7.1391058e-01],
       [7.6650494e-01],
       [9.4616067e-01],
       [9.0685785e-01],
       [5.3313261e-01],
       [5.2254796e-03],
       [9.506143