In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.image as mpimg
from datetime import datetime

### Let's start by processing the colored cats & dog data 

In [2]:
cats_3 = np.load('cats_1000_128_128_3.npy')

In [3]:
dogs_3 = np.load('dogs_1000_128_128_3.npy')

In [4]:
cats_3.shape # investigate the shape

(1000, 128, 128, 3)

In [5]:
dogs_3.shape # investigate the shape

(1000, 128, 128, 3)

In [6]:
cats_3.dtype, dogs_3.dtype # look at dtype

(dtype('float64'), dtype('float64'))

In [7]:
dogs_3_y= np.repeat(1,1000) # Let's create training labels for dogs 

In [8]:
cats_3_y = np.repeat(0,1000) # Let's create training labels for cats

In [9]:
# create labels 1=dog, 0=cat
# combine into one array for training labels
y_train_3 = np.concatenate((dogs_3_y, cats_3_y),axis=0)
y_train_3

array([1, 1, 1, ..., 0, 0, 0])

In [10]:
# combine dogs & cats for training 
x_train_3 = np.concatenate((dogs_3,cats_3),axis=0)
x_train_3

array([[[[118., 116., 128.],
         [106., 104., 119.],
         [120., 118., 131.],
         ...,
         [139., 141., 153.],
         [133., 135., 147.],
         [133., 133., 142.]],

        [[122., 120., 132.],
         [109., 107., 122.],
         [122., 120., 133.],
         ...,
         [141., 143., 155.],
         [137., 138., 151.],
         [136., 136., 145.]],

        [[125., 123., 135.],
         [112., 110., 125.],
         [123., 121., 134.],
         ...,
         [142., 144., 156.],
         [139., 141., 153.],
         [139., 142., 149.]],

        ...,

        [[ 70.,  84.,  87.],
         [ 87.,  90.,  96.],
         [ 73.,  78.,  82.],
         ...,
         [ 67.,  77.,  79.],
         [ 60.,  69.,  72.],
         [ 63.,  73.,  75.]],

        [[ 73.,  78.,  82.],
         [ 69.,  77.,  80.],
         [ 72.,  82.,  84.],
         ...,
         [ 63.,  72.,  77.],
         [ 60.,  69.,  74.],
         [ 75.,  85.,  87.]],

        [[ 68.,  73.,  77.],
       

In [11]:
# create class names
class_names= ['cats','dogs']

### create train, validate & test set

In [12]:
# create train, validate & test set
from sklearn.model_selection import train_test_split

In [13]:
# initial test train split for 3 colors
x_train_3, x_test_3, y_train_3, y_test_3 = train_test_split(x_train_3, y_train_3, test_size=.30, random_state=55)

In [14]:
# train vs validation set
X_train_3, x_valid_3, y_train_3, y_valid_3 = train_test_split(x_train_3,y_train_3, test_size=.20, random_state=55)

In [15]:
X_train_3.shape

(1120, 128, 128, 3)

#### 1st Model

In [16]:
#clear keras session
tf.keras.backend.clear_session()

In [17]:
model1 = keras.models.Sequential([
    keras.layers.Conv2D(filters= 64, kernel_size=(3,3),strides=1, activation='relu', padding='same',
                       input_shape=[128,128,3]),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(pool_size=2, strides=2),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2, strides=2),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2, strides=2),
    keras.layers.Flatten(),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(1000, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(2, activation='softmax')
])

In [18]:
model1.compile(loss="binary_crossentropy", optimizer="nadam", metrics=["accuracy"])

# fit model
time_start = datetime.now()
history1 = model1.fit(X_train_3, y_train_3, epochs=5, validation_data=(x_valid_3, y_valid_3))
time_end = datetime.now()
time_elapsed = time_end - time_start

print('Time elapsed')
print(time_elapsed)
print("Fit model on training data")
history1.history

Epoch 1/5
35/35 [==============================] - 163s 5s/step - loss: 0.9430 - accuracy: 0.5188 - val_loss: 4.3346 - val_accuracy: 0.4500
Epoch 2/5
35/35 [==============================] - 177s 5s/step - loss: 0.8499 - accuracy: 0.5080 - val_loss: 0.7157 - val_accuracy: 0.4821
Epoch 3/5
35/35 [==============================] - 181s 5s/step - loss: 0.8089 - accuracy: 0.5179 - val_loss: 0.6981 - val_accuracy: 0.5429
Epoch 4/5
35/35 [==============================] - 182s 5s/step - loss: 0.7725 - accuracy: 0.5018 - val_loss: 0.7221 - val_accuracy: 0.5464
Epoch 5/5
35/35 [==============================] - 203s 6s/step - loss: 0.7440 - accuracy: 0.5071 - val_loss: 0.6982 - val_accuracy: 0.4429
Time elapsed
0:15:37.653104
Fit model on training data


{'loss': [0.9430389404296875,
  0.849875271320343,
  0.8088871240615845,
  0.772548496723175,
  0.7439581155776978],
 'accuracy': [0.518750011920929,
  0.5080357193946838,
  0.5178571343421936,
  0.5017856955528259,
  0.5071428418159485],
 'val_loss': [4.3346357345581055,
  0.715673565864563,
  0.6980524063110352,
  0.722124457359314,
  0.6981799602508545],
 'val_accuracy': [0.44999998807907104,
  0.4821428656578064,
  0.5428571701049805,
  0.5464285612106323,
  0.44285714626312256]}

In [19]:
print("Evaluate on test data")
score = model1.evaluate(x_test_3, y_test_3)
predictions = model1.predict(x_test_3)
predictions

Evaluate on test data
19/19 [==============================] - 21s 1s/step - loss: 0.6974 - accuracy: 0.4733


array([[0.47074765, 0.52925235],
       [0.462852  , 0.537148  ],
       [0.4505388 , 0.5494612 ],
       ...,
       [0.506216  , 0.4937841 ],
       [0.53833896, 0.46166098],
       [0.44039816, 0.5596018 ]], dtype=float32)

#### 2nd Model

In [20]:
#clear keras session
tf.keras.backend.clear_session()

In [21]:
model2 = keras.models.Sequential([
    keras.layers.Conv2D(filters= 64, kernel_size=3,strides=1, activation='relu', padding='same',
                       input_shape=[128,128,3]),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Flatten(),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(1000, activation='relu'),
    keras.layers.Dropout(0.25),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dropout(0.25),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(2, activation='softmax')
])

In [22]:
optimizer = keras.optimizers.SGD(lr=.02, momentum=0.9, decay=0.01)
model2.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

In [23]:
# fit model
time_start = datetime.now()
history2 = model2.fit(X_train_3, y_train_3, epochs=5, validation_data=(x_valid_3, y_valid_3))
time_end = datetime.now()
time_elapsed = time_end - time_start

print('Time elapsed')
print(time_elapsed)
print("Fit model on training data")
history2.history

Epoch 1/5
35/35 [==============================] - 157s 4s/step - loss: 0.8375 - accuracy: 0.4911 - val_loss: 7.6595 - val_accuracy: 0.4464
Epoch 2/5
35/35 [==============================] - 157s 4s/step - loss: 0.6998 - accuracy: 0.4839 - val_loss: 1.0358 - val_accuracy: 0.4464
Epoch 3/5
35/35 [==============================] - 182s 5s/step - loss: 0.6942 - accuracy: 0.4821 - val_loss: 0.6985 - val_accuracy: 0.4929
Epoch 4/5
35/35 [==============================] - 176s 5s/step - loss: 0.6934 - accuracy: 0.4982 - val_loss: 0.6934 - val_accuracy: 0.5250
Epoch 5/5
35/35 [==============================] - 168s 5s/step - loss: 0.6932 - accuracy: 0.5134 - val_loss: 0.6932 - val_accuracy: 0.5357
Time elapsed
0:14:26.053345
Fit model on training data


{'loss': [0.8375232815742493,
  0.699844479560852,
  0.694226861000061,
  0.6934159994125366,
  0.6932228803634644],
 'accuracy': [0.4910714328289032,
  0.4839285612106323,
  0.4821428656578064,
  0.4982142746448517,
  0.5133928656578064],
 'val_loss': [7.659478664398193,
  1.0357990264892578,
  0.698529839515686,
  0.693350076675415,
  0.6931714415550232],
 'val_accuracy': [0.4464285671710968,
  0.4464285671710968,
  0.4928571283817291,
  0.5249999761581421,
  0.5357142686843872]}

In [24]:
print("Evaluate on test data")
score = model2.evaluate(x_test_3, y_test_3)
predictions = model2.predict(x_test_3)
predictions

Evaluate on test data
19/19 [==============================] - 20s 1s/step - loss: 0.6932 - accuracy: 0.4967


array([[0.50097275, 0.4990273 ],
       [0.5005776 , 0.49942234],
       [0.49440962, 0.50559044],
       ...,
       [0.5021207 , 0.49787936],
       [0.49824727, 0.50175273],
       [0.49730712, 0.5026929 ]], dtype=float32)

#### 3rd Model

In [25]:
#clear keras session
tf.keras.backend.clear_session()

In [26]:
model3 = keras.models.Sequential([
    keras.layers.Conv2D(filters= 64, kernel_size=3,strides=1, activation='relu', padding='same',
                       input_shape=[128,128,3]),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Flatten(),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(1000, activation='relu'),
    keras.layers.Dropout(0.25),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dropout(0.25),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(2, activation='softmax')
])

In [27]:
optimizer=tf.keras.optimizers.Adam(learning_rate=0.001,
                                                 beta_1=0.9,
                                                 beta_2=0.999)
model3.compile(loss=tf.keras.losses.binary_crossentropy,
              optimizer=optimizer,
              metrics=['accuracy'])

In [28]:
# fit model
time_start = datetime.now()
history3 = model3.fit(X_train_3, y_train_3, epochs=5, validation_data=(x_valid_3, y_valid_3))
time_end = datetime.now()
time_elapsed = time_end - time_start

print('Time elapsed')
print(time_elapsed)
print("Fit model on training data")
history3.history

Epoch 1/5
35/35 [==============================] - 166s 5s/step - loss: 0.9192 - accuracy: 0.4911 - val_loss: 7.5063 - val_accuracy: 0.4464
Epoch 2/5
35/35 [==============================] - 184s 5s/step - loss: 0.8137 - accuracy: 0.5000 - val_loss: 1.4621 - val_accuracy: 0.5000
Epoch 3/5
35/35 [==============================] - 173s 5s/step - loss: 0.7815 - accuracy: 0.5116 - val_loss: 1.9691 - val_accuracy: 0.5500
Epoch 4/5
35/35 [==============================] - 171s 5s/step - loss: 0.7722 - accuracy: 0.5071 - val_loss: 0.9387 - val_accuracy: 0.5250
Epoch 5/5
35/35 [==============================] - 193s 6s/step - loss: 0.7466 - accuracy: 0.5152 - val_loss: 0.7475 - val_accuracy: 0.5429
Time elapsed
0:15:15.070698
Fit model on training data


{'loss': [0.9192102551460266,
  0.8137125968933105,
  0.7815183997154236,
  0.7722200155258179,
  0.7466049194335938],
 'accuracy': [0.4910714328289032,
  0.5,
  0.5116071701049805,
  0.5071428418159485,
  0.5151785612106323],
 'val_loss': [7.506314754486084,
  1.4621055126190186,
  1.9690730571746826,
  0.938718318939209,
  0.7475073933601379],
 'val_accuracy': [0.4464285671710968,
  0.5,
  0.550000011920929,
  0.5249999761581421,
  0.5428571701049805]}

In [29]:
print("Evaluate on test data")
score = model3.evaluate(x_test_3, y_test_3)
predictions = model3.predict(x_test_3)
predictions

Evaluate on test data
19/19 [==============================] - 23s 1s/step - loss: 0.7485 - accuracy: 0.4683


array([[0.71046466, 0.2895354 ],
       [0.4165964 , 0.58340365],
       [0.5151246 , 0.48487535],
       ...,
       [0.65270674, 0.3472932 ],
       [0.62614465, 0.3738553 ],
       [0.7704488 , 0.22955123]], dtype=float32)

#### 4th Model

In [30]:
#clear keras session
tf.keras.backend.clear_session()

In [31]:
model4 = keras.models.Sequential([
    keras.layers.Conv2D(filters= 64, kernel_size=(3,3),strides=1, activation='relu', padding='same',
                       input_shape=[128,128,3]),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.Conv2D(128,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.Conv2D(256,3, activation='relu',padding='same'),
    keras.layers.MaxPooling2D(pool_size=2),
    keras.layers.Flatten(),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(1000, activation='relu'),
    keras.layers.Dropout(0.25),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dropout(0.25),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(2, activation='softmax')
])

In [32]:
optimizer=tf.keras.optimizers.Adam(learning_rate=0.001,
                                                 beta_1=0.9,
                                                 beta_2=0.999)
model4.compile(loss=tf.keras.losses.binary_crossentropy,
              optimizer=optimizer,
              metrics=['accuracy'])

In [33]:
# fit model
time_start = datetime.now()
history4 = model4.fit(X_train_3, y_train_3, epochs=30, validation_data=(x_valid_3, y_valid_3))
time_end = datetime.now()
time_elapsed = time_end - time_start

print('Time elapsed')
print(time_elapsed)
print("Fit model on training data")
history4.history

Epoch 1/30
35/35 [==============================] - 148s 4s/step - loss: 0.8935 - accuracy: 0.4964 - val_loss: 5.1348 - val_accuracy: 0.5393
Epoch 2/30
35/35 [==============================] - 143s 4s/step - loss: 0.8098 - accuracy: 0.4884 - val_loss: 1.6549 - val_accuracy: 0.5143
Epoch 3/30
35/35 [==============================] - 138s 4s/step - loss: 0.7871 - accuracy: 0.5152 - val_loss: 0.8480 - val_accuracy: 0.5000
Epoch 4/30
35/35 [==============================] - 128s 4s/step - loss: 0.7616 - accuracy: 0.4786 - val_loss: 0.7294 - val_accuracy: 0.5321
Epoch 5/30
35/35 [==============================] - 127s 4s/step - loss: 0.7451 - accuracy: 0.5196 - val_loss: 0.7055 - val_accuracy: 0.5714
Epoch 6/30
35/35 [==============================] - 124s 4s/step - loss: 0.7299 - accuracy: 0.4982 - val_loss: 0.7198 - val_accuracy: 0.5143
Epoch 7/30
35/35 [==============================] - 235s 7s/step - loss: 0.7235 - accuracy: 0.5143 - val_loss: 0.7050 - val_accuracy: 0.4964
Epoch 8/30
35

{'loss': [0.893451988697052,
  0.8098247051239014,
  0.7870779037475586,
  0.7616016268730164,
  0.7450919151306152,
  0.7299392223358154,
  0.7235498428344727,
  0.7150565385818481,
  0.7110903263092041,
  0.7062570452690125,
  0.7015829086303711,
  0.6993505954742432,
  0.6972599625587463,
  0.6961533427238464,
  0.6954903602600098,
  0.6946434378623962,
  0.6939894556999207,
  0.6936895251274109,
  0.6935034394264221,
  0.6933761239051819,
  0.6933070421218872,
  0.6932669281959534,
  0.6932176947593689,
  0.6931871175765991,
  0.6931712627410889,
  0.6931636929512024,
  0.6931569576263428,
  0.6931530237197876,
  0.6931505799293518,
  0.6931489109992981],
 'accuracy': [0.49642857909202576,
  0.4883928596973419,
  0.5151785612106323,
  0.47857141494750977,
  0.5196428298950195,
  0.4982142746448517,
  0.5142857432365417,
  0.5017856955528259,
  0.5321428775787354,
  0.49464285373687744,
  0.5035714507102966,
  0.5116071701049805,
  0.5017856955528259,
  0.5080357193946838,
  0.52142

In [34]:
print("Evaluate on test data")
score = model4.evaluate(x_test_3, y_test_3)
predictions = model4.predict(x_test_3)
predictions

Evaluate on test data
19/19 [==============================] - 20s 1s/step - loss: 0.6931 - accuracy: 0.5033


array([[0.49984252, 0.50015754],
       [0.49961546, 0.5003845 ],
       [0.50019634, 0.49980366],
       ...,
       [0.5002598 , 0.49974012],
       [0.49968863, 0.5003113 ],
       [0.50026023, 0.49973977]], dtype=float32)